#!/bin/bash

cp extract/jars/aggdesigner-algorithm-6.0.jar extract/spark-3.3.1-bin-hadoop3/jars/aggdesigner-algorithm-6.0.jar
cp extract/jars/all-1.1.2.pom extract/spark-3.3.1-bin-hadoop3/jars/all-1.1.2.pom
cp extract/jars/animal-sniffer-annotations-1.14.jar extract/spark-3.3.1-bin-hadoop3/jars/animal-sniffer-annotations-1.14.jar
cp extract/jars/aopalliance-1.0.jar extract/spark-3.3.1-bin-hadoop3/jars/aopalliance-1.0.jar
cp extract/jars/aws-glue-datacatalog-client-common-3.7.0.jar extract/spark-3.3.1-bin-hadoop3/jars/aws-glue-datacatalog-client-common-3.7.0.jar
cp extract/jars/aws-glue-datacatalog-hive3-client-3.7.0.jar extract/spark-3.3.1-bin-hadoop3/jars/aws-glue-datacatalog-hive3-client-3.7.0.jar
cp extract/jars/aws-glue-datacatalog-spark-client-3.7.0.jar extract/spark-3.3.1-bin-hadoop3/jars/aws-glue-datacatalog-spark-client-3.7.0.jar
cp extract/jars/bcprov-ext-jdk15on-1.66.jar extract/spark-3.3.1-bin-hadoop3/jars/bcprov-ext-jdk15on-1.66.jar
cp extract/jars/checker-qual-2.5.2.jar extract/spark-3.3.1-bin-hadoop3/jars/checker-qual-2.5.2.jar
cp extract/jars/com.amazonaws_aws-java-sdk-bundle-1.11.1026.jar extract/spark-3.3.1-bin-hadoop3/jars/com.amazonaws_aws-java-sdk-bundle-1.11.1026.jar
cp extract/jars/commons-text-1.10.0.jar extract/spark-3.3.1-bin-hadoop3/jars/commons-text-1.10.0.jar
cp extract/jars/disruptor-3.3.7.jar extract/spark-3.3.1-bin-hadoop3/jars/disruptor-3.3.7.jar
cp extract/jars/emr-spark-goodies.jar extract/spark-3.3.1-bin-hadoop3/jars/emr-spark-goodies.jar
cp extract/jars/emrfs-hadoop-assembly-2.54.0.jar extract/spark-3.3.1-bin-hadoop3/jars/emrfs-hadoop-assembly-2.54.0.jar
cp extract/jars/error_prone_annotations-2.1.3.jar extract/spark-3.3.1-bin-hadoop3/jars/error_prone_annotations-2.1.3.jar
cp extract/jars/findbugs-annotations-3.0.1.jar extract/spark-3.3.1-bin-hadoop3/jars/findbugs-annotations-3.0.1.jar
cp extract/jars/gmetric4j-1.0.10.jar extract/spark-3.3.1-bin-hadoop3/jars/gmetric4j-1.0.10.jar
cp extract/jars/gson-2.8.6.jar extract/spark-3.3.1-bin-hadoop3/jars/gson-2.8.6.jar
cp extract/jars/hadoop-client-api-3.3.3-amzn-0.jar extract/spark-3.3.1-bin-hadoop3/jars/hadoop-client-api-3.3.3-amzn-0.jar
cp extract/jars/hadoop-client-runtime-3.3.3-amzn-0.jar extract/spark-3.3.1-bin-hadoop3/jars/hadoop-client-runtime-3.3.3-amzn-0.jar
cp extract/jars/hadoop-yarn-server-web-proxy-3.3.3-amzn-0.jar extract/spark-3.3.1-bin-hadoop3/jars/hadoop-yarn-server-web-proxy-3.3.3-amzn-0.jar
cp extract/jars/hive-beeline-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-beeline-2.3.9-amzn-2.jar
cp extract/jars/hive-cli-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-cli-2.3.9-amzn-2.jar
cp extract/jars/hive-common-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-common-2.3.9-amzn-2.jar
cp extract/jars/hive-exec-2.3.9-amzn-2-core.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-exec-2.3.9-amzn-2-core.jar
cp extract/jars/hive-jdbc-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-jdbc-2.3.9-amzn-2.jar
cp extract/jars/hive-llap-common-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-llap-common-2.3.9-amzn-2.jar
cp extract/jars/hive-metastore-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-metastore-2.3.9-amzn-2.jar
cp extract/jars/hive-serde-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-serde-2.3.9-amzn-2.jar
cp extract/jars/hive-shims-0.23-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-shims-0.23-2.3.9-amzn-2.jar
cp extract/jars/hive-shims-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-shims-2.3.9-amzn-2.jar
cp extract/jars/hive-shims-common-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-shims-common-2.3.9-amzn-2.jar
cp extract/jars/hive-shims-scheduler-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-shims-scheduler-2.3.9-amzn-2.jar
cp extract/jars/hive-vector-code-gen-2.3.9-amzn-2.jar extract/spark-3.3.1-bin-hadoop3/jars/hive-vector-code-gen-2.3.9-amzn-2.jar
cp extract/jars/ion-java-1.0.2.jar extract/spark-3.3.1-bin-hadoop3/jars/ion-java-1.0.2.jar
cp extract/jars/j2objc-annotations-1.1.jar extract/spark-3.3.1-bin-hadoop3/jars/j2objc-annotations-1.1.jar
cp extract/jars/javax.inject-1.jar extract/spark-3.3.1-bin-hadoop3/jars/javax.inject-1.jar
cp extract/jars/javax.servlet-api-3.1.0.jar extract/spark-3.3.1-bin-hadoop3/jars/javax.servlet-api-3.1.0.jar
cp extract/jars/jetty-rewrite-9.3.27.v20190418.jar extract/spark-3.3.1-bin-hadoop3/jars/jetty-rewrite-9.3.27.v20190418.jar
cp extract/jars/jmespath-java-1.12.331.jar extract/spark-3.3.1-bin-hadoop3/jars/jmespath-java-1.12.331.jar
cp extract/jars/jniloader-1.1.jar extract/spark-3.3.1-bin-hadoop3/jars/jniloader-1.1.jar
cp extract/jars/jsr305-3.0.2.jar extract/spark-3.3.1-bin-hadoop3/jars/jsr305-3.0.2.jar
cp extract/jars/mariadb-connector-java.jar extract/spark-3.3.1-bin-hadoop3/jars/mariadb-connector-java.jar
cp extract/jars/native_ref-java-1.1.jar extract/spark-3.3.1-bin-hadoop3/jars/native_ref-java-1.1.jar
cp extract/jars/native_system-java-1.1.jar extract/spark-3.3.1-bin-hadoop3/jars/native_system-java-1.1.jar
cp extract/jars/netlib-native_ref-linux-armhf-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_ref-linux-armhf-1.1-natives.jar
cp extract/jars/netlib-native_ref-linux-i686-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_ref-linux-i686-1.1-natives.jar
cp extract/jars/netlib-native_ref-linux-x86_64-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_ref-linux-x86_64-1.1-natives.jar
cp extract/jars/netlib-native_ref-osx-x86_64-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_ref-osx-x86_64-1.1-natives.jar
cp extract/jars/netlib-native_ref-win-i686-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_ref-win-i686-1.1-natives.jar
cp extract/jars/netlib-native_ref-win-x86_64-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_ref-win-x86_64-1.1-natives.jar
cp extract/jars/netlib-native_system-linux-armhf-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_system-linux-armhf-1.1-natives.jar
cp extract/jars/netlib-native_system-linux-i686-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_system-linux-i686-1.1-natives.jar
cp extract/jars/netlib-native_system-linux-x86_64-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_system-linux-x86_64-1.1-natives.jar
cp extract/jars/netlib-native_system-osx-x86_64-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_system-osx-x86_64-1.1-natives.jar
cp extract/jars/netlib-native_system-win-i686-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_system-win-i686-1.1-natives.jar
cp extract/jars/netlib-native_system-win-x86_64-1.1-natives.jar extract/spark-3.3.1-bin-hadoop3/jars/netlib-native_system-win-x86_64-1.1-natives.jar
cp extract/jars/org.antlr_antlr4-runtime-4.8.jar extract/spark-3.3.1-bin-hadoop3/jars/org.antlr_antlr4-runtime-4.8.jar
cp extract/jars/org.apache.hadoop_hadoop-aws-3.3.3.jar extract/spark-3.3.1-bin-hadoop3/jars/org.apache.hadoop_hadoop-aws-3.3.3.jar
cp extract/jars/org.codehaus.jackson_jackson-core-asl-1.9.13.jar extract/spark-3.3.1-bin-hadoop3/jars/org.codehaus.jackson_jackson-core-asl-1.9.13.jar
cp extract/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar extract/spark-3.3.1-bin-hadoop3/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar
cp extract/jars/parquet-column-1.12.2-amzn-1.jar extract/spark-3.3.1-bin-hadoop3/jars/parquet-column-1.12.2-amzn-1.jar
cp extract/jars/parquet-common-1.12.2-amzn-1.jar extract/spark-3.3.1-bin-hadoop3/jars/parquet-common-1.12.2-amzn-1.jar
cp extract/jars/parquet-encoding-1.12.2-amzn-1.jar extract/spark-3.3.1-bin-hadoop3/jars/parquet-encoding-1.12.2-amzn-1.jar
cp extract/jars/parquet-format-structures-1.12.2-amzn-1.jar extract/spark-3.3.1-bin-hadoop3/jars/parquet-format-structures-1.12.2-amzn-1.jar
cp extract/jars/parquet-hadoop-1.12.2-amzn-1.jar extract/spark-3.3.1-bin-hadoop3/jars/parquet-hadoop-1.12.2-amzn-1.jar
cp extract/jars/parquet-jackson-1.12.2-amzn-1.jar extract/spark-3.3.1-bin-hadoop3/jars/parquet-jackson-1.12.2-amzn-1.jar
cp extract/jars/remotetea-oncrpc-1.1.2.jar extract/spark-3.3.1-bin-hadoop3/jars/remotetea-oncrpc-1.1.2.jar
cp extract/jars/snakeyaml-1.30.jar extract/spark-3.3.1-bin-hadoop3/jars/snakeyaml-1.30.jar

echo "Jars copied to spark-3.3.1-bin-hadoop3/jars"